version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
  back:
    build:
      context: ./chatapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - ./chatapp:/app
      - /app/node_modules
  react:
    build:
      context: ./chatapp-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/node_modules
      - ./chatapp-client:/app