name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y ssh-client

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem docker-compose.yml $SERVER_USER@$SERVER_IP:/path/on/server/
        scp -i private_key.pem -r app/chatapp $SERVER_USER@$SERVER_IP:/path/on/server/app/
        scp -i private_key.pem -r app/chatapp-client $SERVER_USER@$SERVER_IP:/path/on/server/app/
        ssh -i private_key.pem $SERVER_USER@$SERVER_IP "cd /path/on/server && docker-compose up -d"
        rm -f private_key.pem
