name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_n_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: 3.34.45.12
        username: ubuntu
        key: ${{ secrets.HOME }}
        port: 22
        script: echo 'SSH Successful'
    # 캐시 문제를 해결하기 위해 --no-cache 옵션을 추가
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.34.45.12
        username: ubuntu
        key: ${{ secrets.HOME }}
        port: 22 # ssh default port 22
        script: |
          echo 'UBUNTU DEPLOY START'
          echo 'CHATAPP BACK DEPLOY START'
          cd /home/ubuntu/chatapp_back
          git pull
          sudo docker-compose build #--no-cache 
          # sudo docker-compose down
          sudo docker-compose up -d
